pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release-Windows'

steps:
- script: |
    dotnet build AudioWorks\AudioWorks.sln --configuration $(buildConfiguration)
  displayName: 'Build $(buildConfiguration) configuration'

- powershell: |
    Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
    Invoke-WebRequest -Uri https://audioworks.blob.core.windows.net/prerequisites/AppleApplicationSupport.msi -OutFile AppleApplicationSupport.msi
    Invoke-WebRequest -Uri https://audioworks.blob.core.windows.net/prerequisites/AppleApplicationSupport64.msi -OutFile AppleApplicationSupport64.msi
  displayName: 'Download prerequisites'

- script: |
    COPY /Y nuget.exe "%SystemRoot%\System32"
    msiexec /i AppleApplicationSupport.msi /qb-
    msiexec /i AppleApplicationSupport64.msi /qb-
  displayName: 'Install prerequisites'

- powershell: |
    $settingsDir = "$([System.Environment]::GetFolderPath(28))\AudioWorks"
    $localFeedDir = (New-Item "$settingsDir\LocalFeed" -ItemType Directory).FullName
    Get-ChildItem -Path AudioWorks\src\Extensions -Filter *.nupkg -Recurse | Select-Object -ExpandProperty FullName | % { nuget add $_ -Source $localFeedDir -NonInteractive }
    $content = Get-Content AudioWorks\src\AudioWorks.Common\settings.json | ConvertFrom-Json
    $content.EnableTelemetry = $false
    $content.ExtensionRepository = $localFeedDir
    $content | ConvertTo-Json | Set-Content "$settingsDir\settings.json"
  displayName: 'Configuring AudioWorks for testing'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'AudioWorks/tests/*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'