pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release-Windows'

steps:
- script: |
    dotnet build AudioWorks\AudioWorks.sln --configuration $(buildConfiguration)
  displayName: 'Build $(buildConfiguration) configuration'

- powershell: |
    Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile nuget.exe
    Invoke-WebRequest -Uri https://audioworks.blob.core.windows.net/prerequisites/AppleApplicationSupport.msi -OutFile AppleApplicationSupport.msi
    Invoke-WebRequest -Uri https://audioworks.blob.core.windows.net/prerequisites/AppleApplicationSupport64.msi -OutFile AppleApplicationSupport64.msi
  displayName: 'Download prerequisites'

- script: |
    COPY /Y nuget.exe "%SystemRoot%\System32"
    msiexec /i AppleApplicationSupport.msi /qb-
    msiexec /i AppleApplicationSupport64.msi /qb-
    dotnet tool install --global dotnet-reportgenerator-globaltool
  displayName: 'Install prerequisites'

- powershell: |
    $settingsDir = "$([System.Environment]::GetFolderPath(28))\AudioWorks"
    $localFeedDir = (New-Item "$settingsDir\LocalFeed" -ItemType Directory).FullName
    Get-ChildItem -Path AudioWorks\src\Extensions -Filter *.nupkg -Recurse | Select-Object -ExpandProperty FullName | % { nuget add $_ -Source $localFeedDir -NonInteractive }
    $content = Get-Content AudioWorks\src\AudioWorks.Common\settings.json | ConvertFrom-Json
    $content.EnableTelemetry = $false
    $content.ExtensionRepository = $localFeedDir
    $content | ConvertTo-Json | Set-Content "$settingsDir\settings.json"
  displayName: 'Configure extensions for testing'

- script: |
    dotnet test AudioWorks\tests\AudioWorks.Common.Tests --no-build --logger trx --framework netcoreapp2.1 --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutput=.\coverage.netcoreapp2.1.json /p:Exclude="[AudioWorks.*.Tests]*,[AudioWorks.TestUtilities]*,[*]JetBrains.Annotations.*" /p:IncludeDirectory="%LOCALAPPDATA%\AudioWorks\Extensions\netcoreapp2.1\*"
    dotnet test AudioWorks\tests\AudioWorks.Common.Tests --no-build --logger trx --framework net471 --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutput=.\coverage.merged.json /p:Exclude="[AudioWorks.*.Tests]*,[AudioWorks.TestUtilities]*,[*]JetBrains.Annotations.*" /p:IncludeDirectory="%LOCALAPPDATA%\AudioWorks\Extensions\netstandard2.0\*" /p:MergeWith=.\coverage.netcoreapp2.1.json
    dotnet test AudioWorks\tests\AudioWorks.Extensibility.Tests --no-build --logger trx --framework netcoreapp2.1 --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutput=.\coverage.netcoreapp2.1.json /p:Exclude="[AudioWorks.*.Tests]*,[AudioWorks.TestUtilities]*,[*]JetBrains.Annotations.*" /p:IncludeDirectory="%LOCALAPPDATA%\AudioWorks\Extensions\netcoreapp2.1\*" /p:MergeWith=$(Build.SourcesDirectory)\AudioWorks\tests\AudioWorks.Common.Tests\coverage.merged.json
    dotnet test AudioWorks\tests\AudioWorks.Extensibility.Tests --no-build --logger trx --framework net471 --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutput=.\coverage.merged.json /p:Exclude="[AudioWorks.*.Tests]*,[AudioWorks.TestUtilities]*,[*]JetBrains.Annotations.*" /p:IncludeDirectory="%LOCALAPPDATA%\AudioWorks\Extensions\netstandard2.0\*" /p:MergeWith=.\coverage.netcoreapp2.1.json
    dotnet test AudioWorks\tests\AudioWorks.Api.Tests --no-build --logger trx --framework netcoreapp2.1 --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutput=.\coverage.netcoreapp2.1.json /p:Exclude="[AudioWorks.*.Tests]*,[AudioWorks.TestUtilities]*,[*]JetBrains.Annotations.*" /p:IncludeDirectory="%LOCALAPPDATA%\AudioWorks\Extensions\netcoreapp2.1\*" /p:MergeWith=$(Build.SourcesDirectory)\AudioWorks\tests\AudioWorks.Extensibility.Tests\coverage.merged.json
    dotnet test AudioWorks\tests\AudioWorks.Api.Tests --no-build --logger trx --framework net471 --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutput=.\coverage.merged.json /p:Exclude="[AudioWorks.*.Tests]*,[AudioWorks.TestUtilities]*,[*]JetBrains.Annotations.*" /p:IncludeDirectory="%LOCALAPPDATA%\AudioWorks\Extensions\netstandard2.0\*" /p:MergeWith=.\coverage.netcoreapp2.1.json
    dotnet test AudioWorks\tests\AudioWorks.Commands.Tests --no-build --logger trx --framework netcoreapp2.1 --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutput=.\coverage.netcoreapp2.1.json /p:Exclude="[AudioWorks.*.Tests]*,[AudioWorks.TestUtilities]*,[*]JetBrains.Annotations.*" /p:IncludeDirectory="%LOCALAPPDATA%\AudioWorks\Extensions\netcoreapp2.1\*,AudioWorks.Commands\netcoreapp2.1" /p:MergeWith=$(Build.SourcesDirectory)\AudioWorks\tests\AudioWorks.Api.Tests\coverage.merged.json
    dotnet test AudioWorks\tests\AudioWorks.Commands.Tests --no-build --logger trx --framework net471 --configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)\coverage.xml /p:Exclude="[AudioWorks.*.Tests]*,[AudioWorks.TestUtilities]*,[*]JetBrains.Annotations.*" /p:IncludeDirectory="%LOCALAPPDATA%\AudioWorks\Extensions\netstandard2.0\*,AudioWorks.Commands\netstandard2.0" /p:MergeWith=.\coverage.netcoreapp2.1.json
    %USERPROFILE%\.dotnet\tools\reportgenerator "-reports:coverage.xml" "-targetdir:reports" "-reporttypes:HTMLInline;HTMLChart"
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  inputs:
    codecoverageTool: cobertura
    summaryFileLocation: $(Build.SourcesDirectory)\coverage.xml
    reportDirectory: $(Build.SourcesDirectory)\reports