pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release-Windows'

steps:
- script: dotnet build AudioWorks\AudioWorks.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: powershell -ExecutionPolicy Bypass -Command "& { Invoke-WebRequest -Uri https://audioworks.blob.core.windows.net/prerequisites/AppleApplicationSupport.msi -OutFile AppleApplicationSupport.msi }"
  displayName: 'Download AppleApplicationSupport.msi'
- script: msiexec /i AppleApplicationSupport.msi /qb-
  displayName: 'Install AppleApplicationSupport.msi'
- script: powershell -ExecutionPolicy Bypass -Command "& { Invoke-WebRequest -Uri https://audioworks.blob.core.windows.net/prerequisites/AppleApplicationSupport64.msi -OutFile AppleApplicationSupport64.msi }"
  displayName: 'Download AppleApplicationSupport64.msi'
- script: msiexec /i AppleApplicationSupport64.msi /qb-
  displayName: 'Install AppleApplicationSupport64.msi'
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'AudioWorks/tests/*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'